name: docker action

on: push

jobs:
  docker-action:
    runs-on: ubuntu-latest
    steps:
      - name: docker-call
        id: hello
        uses: vamshi-kk/Github-Actions-Demo/dockerfolder@v1-alpha
        with:
          who-to-greet: 'Vamshi'
      - name: Print output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
